var defaults = require('lodash/defaults.js')

var commonData = {
  year: 2015
, createdAt: new Date()
, updatedAt: new Date()
}

module.exports = {
  up: function (queryInterface) {
    return queryInterface.bulkInsert('movies', [
      defaults({title: "45 Years"}, commonData)
    , defaults({title: "99 Homes"}, commonData)
    , defaults({title: "A War"}, commonData)
    , defaults({title: "Amy"}, commonData)
    , defaults({title: "Anomalisa"}, commonData)
    , defaults({title: "Beasts of No Nation"}, commonData)
    , defaults({title: "Bridge of Spies"}, commonData)
    , defaults({title: "Brooklyn"}, commonData)
    , defaults({title: "Carol"}, commonData)
    , defaults({title: "Cartel Land"}, commonData)
    , defaults({title: "Cinderella"}, commonData)
    , defaults({title: "Concussion"}, commonData)
    , defaults({title: "Creed"}, commonData)
    , defaults({title: "Danny Collins"}, commonData)
    , defaults({title: "Embrace of the Serpent"}, commonData)
    , defaults({title: "Ex Machina"}, commonData)
    , defaults({title: "Fifty Shades of Grey"}, commonData)
    , defaults({title: "Furious 7"}, commonData)
    , defaults({title: "Grandma"}, commonData)
    , defaults({title: "Infinitely Polar Bear"}, commonData)
    , defaults({title: "Inside Out"}, commonData)
    , defaults({title: "Joy"}, commonData)
    , defaults({title: "Love & Mercy"}, commonData)
    , defaults({title: "Mad Max: Fury Road"}, commonData)
    , defaults({title: "Mustang"}, commonData)
    , defaults({title: "Racing Extinction"}, commonData)
    , defaults({title: "Room"}, commonData)
    , defaults({title: "Shaun the Sheep Movie"}, commonData)
    , defaults({title: "Sicario"}, commonData)
    , defaults({title: "Son of Saul"}, commonData)
    , defaults({title: "Spotlight"}, commonData)
    , defaults({title: "Spy"}, commonData)
    , defaults({title: "Steve Jobs"}, commonData)
    , defaults({title: "Straight Outta Compton"}, commonData)
    , defaults({title: "Spectre"}, commonData)
    , defaults({title: "Star Wars: The Force Awakens"}, commonData)
    , defaults({title: "The 100-Year-Old Man Who Climbed out the Window and Disappeared"}, commonData)
    , defaults({title: "The Big Short"}, commonData)
    , defaults({title: "The Boy and the World"}, commonData)
    , defaults({title: "The Brand New Testament"}, commonData)
    , defaults({title: "The Club"}, commonData)
    , defaults({title: "The Danish Girl"}, commonData)
    , defaults({title: "The Fencer"}, commonData)
    , defaults({title: "The Good Dinosaur"}, commonData)
    , defaults({title: "The Hateful Eight"}, commonData)
    , defaults({title: "The Hunting Ground"}, commonData)
    , defaults({title: "The Lady in the Van"}, commonData)
    , defaults({title: "The Look of Silence"}, commonData)
    , defaults({title: "The Martian"}, commonData)
    , defaults({title: "The Peanuts Movie"}, commonData)
    , defaults({title: "The Revenant"}, commonData)
    , defaults({title: "Theeb"}, commonData)
    , defaults({title: "Trainwreck"}, commonData)
    , defaults({title: "Trumbo"}, commonData)
    , defaults({title: "What Happened, Miss Simone?"}, commonData)
    , defaults({title: "When Marnie Was There"}, commonData)
    , defaults({title: "Winter on Fire: Ukraine's Fight for Freedom"}, commonData)
    , defaults({title: "Youth"}, commonData)
    ])
  },

  down: function (queryInterface) {
    return queryInterface.bulkDelete('movies', null, {})
  }
}
