var defaults = require('lodash/defaults.js')

var commonData = {
  createdAt: new Date()
, updatedAt: new Date()
}

module.exports = {
  up: function (queryInterface) {
    return queryInterface.bulkInsert('persons', [
      defaults({name: 'Aaron Sorkin'}, commonData)
    , defaults({name: 'Adam McKay'}, commonData)
    , defaults({name: 'Al Pacino'}, commonData)
    , defaults({name: 'Alan Robert Murray'}, commonData)
    , defaults({name: 'Alejandro Iñárritu'}, commonData)
    , defaults({name: 'Alex Garland'}, commonData)
    , defaults({name: 'Alexandre Desplat'}, commonData)
    , defaults({name: 'Alicia Vikander'}, commonData)
    , defaults({name: 'Alva Noto'}, commonData)
    , defaults({name: 'Amy Schumer'}, commonData)
    , defaults({name: 'Andrea Berloff'}, commonData)
    , defaults({name: 'Brie Larson'}, commonData)
    , defaults({name: 'Bryan Cranston'}, commonData)
    , defaults({name: 'Carter Burwell'}, commonData)
    , defaults({name: 'Cate Blanchett'}, commonData)
    , defaults({name: 'Charles Randolph'}, commonData)
    , defaults({name: 'Charlotte Rampling'}, commonData)
    , defaults({name: 'Christian Bale'}, commonData)
    , defaults({name: 'Daniel Pemberton'}, commonData)
    , defaults({name: 'David Acord'}, commonData)
    , defaults({name: 'David White'}, commonData)
    , defaults({name: 'Drew Goddard'}, commonData)
    , defaults({name: 'Ed Lachman'}, commonData)
    , defaults({name: 'Eddie Redmayne'}, commonData)
    , defaults({name: 'Emma Donoghue'}, commonData)
    , defaults({name: 'Emmanuel Lubezki'}, commonData)
    , defaults({name: 'Ennio Morricone'}, commonData)
    , defaults({name: 'Ethan Coen'}, commonData)
    , defaults({name: 'George Miller'}, commonData)
    , defaults({name: 'Hank Corwin'}, commonData)
    , defaults({name: 'Helen Mirren'}, commonData)
    , defaults({name: 'Idris Elba'}, commonData)
    , defaults({name: 'Jacqueline West'}, commonData)
    , defaults({name: 'Jane Fonda'}, commonData)
    , defaults({name: 'Jennifer Jason Leigh'}, commonData)
    , defaults({name: 'Jennifer Lawrence'}, commonData)
    , defaults({name: 'Jenny Beavan'}, commonData)
    , defaults({name: 'Joel Coen'}, commonData)
    , defaults({name: 'Jóhann Jóhannsson'}, commonData)
    , defaults({name: 'John Seale'}, commonData)
    , defaults({name: 'John Williams'}, commonData)
    , defaults({name: 'Jonathan Herman'}, commonData)
    , defaults({name: 'Josh Singer'}, commonData)
    , defaults({name: 'Kate Winslet'}, commonData)
    , defaults({name: 'Leonardo DiCaprio'}, commonData)
    , defaults({name: 'Lenny Abrahamson'}, commonData)
    , defaults({name: 'Lily Tomlin'}, commonData)
    , defaults({name: 'Lon Bender'}, commonData)
    , defaults({name: 'Maggie Smith'}, commonData)
    , defaults({name: 'Mark Mangini'}, commonData)
    , defaults({name: 'Mark Ruffalo'}, commonData)
    , defaults({name: 'Mark Rylance'}, commonData)
    , defaults({name: 'Margaret Sixel'}, commonData)
    , defaults({name: 'Martin Hernandez'}, commonData)
    , defaults({name: 'Mary Jo Markey'}, commonData)
    , defaults({name: 'Maryann Brandon'}, commonData)
    , defaults({name: 'Matt Charman'}, commonData)
    , defaults({name: 'Matt Damon'}, commonData)
    , defaults({name: 'Matthew Wood'}, commonData)
    , defaults({name: 'Meg LeFauve'}, commonData)
    , defaults({name: 'Melissa McCarthy'}, commonData)
    , defaults({name: 'Michael Fassbender'}, commonData)
    , defaults({name: 'Michael Shannon'}, commonData)
    , defaults({name: 'Nick Hornby'}, commonData)
    , defaults({name: 'Oliver Tarney'}, commonData)
    , defaults({name: 'Paco Delgado'}, commonData)
    , defaults({name: 'Paul Dano'}, commonData)
    , defaults({name: 'Pete Docter'}, commonData)
    , defaults({name: 'Phyllis Nagy'}, commonData)
    , defaults({name: 'Quentin Tarantino'}, commonData)
    , defaults({name: 'Rachel McAdams'}, commonData)
    , defaults({name: 'Ridley Scott'}, commonData)
    , defaults({name: 'Robert Richardson'}, commonData)
    , defaults({name: 'Roger Deakins'}, commonData)
    , defaults({name: 'Rooney Mara'}, commonData)
    , defaults({name: 'Ryuichi Sakamoto'}, commonData)
    , defaults({name: 'Sandy Powell'}, commonData)
    , defaults({name: 'Saoirse Ronan'}, commonData)
    , defaults({name: 'Stephen Mirrione'}, commonData)
    , defaults({name: 'Steve Carell'}, commonData)
    , defaults({name: 'Sylvester Stallone'}, commonData)
    , defaults({name: 'Thomas Newman'}, commonData)
    , defaults({name: 'Todd Haynes'}, commonData)
    , defaults({name: 'Tom Hardy'}, commonData)
    , defaults({name: 'Tom McArdle'}, commonData)
    , defaults({name: 'Tom McCarthy'}, commonData)
    , defaults({name: 'Will Smith'}, commonData)
    ])
  }

, down: function (queryInterface) {
    return queryInterface.bulkDelete('persons', null, {})
  }
}
